### ISSUE TITLE
Menu changes

### ISSUE THREAD

**Issue by mvchn** [trngl8/python-training-level3#1]
1. Get user input
2. Print the proper line title (no digits and other symbols, the first letter should be capitalized) 

expected:

```
$ python3 menu.py

[1]. data structures (list, dict, tuple, set)
[2]. functions
[3]. filesystem operations
[4]. exceptions
[5]. objects details and abstractions
[6]. database
[7]. web application

Input your choice: 

```

The program should print line by choice id

**Comment by savag21** [comment]
no numbers or other symbols. what about spaces?

**Comment by mvchn** [comment]
@savag21 you may not implement the requirements in the brackets
